### PR TITLE
Add a lot of functions by Dinghow

### PR DESCRIPTION
**Pull request by Dinghow**
I've done a lot of work to the hexo theme. You can see the details in README
- Add Disqus
- Add livere
- Add Addthis
- Add About page
- Add Friend link page
- Add multi-language support
- Add inner math type support (install hexo-math at first and may need proxy)
- Support edit favicon in _config.yml 
- Fix some syntax error

### CODE REVIEW

**Comment by Sariay** [comment]
Firstly，thanks for your good work！ @Dinghow 

Secondly, I am refactoring this project recently. （Including its css, ejs...）

Thirdly，I will refer to your ‘commits’ and indicate the contribution of you.

**Comment by Dinghow** [comment]
Fine, I hope this project could be better and better~

**Comment by Sariay** [comment]
@Dinghow 

Hello, maybe you need to **redo** About-page and  Friend-link-page，describe in detail how to use the gitalk script！

If you are willing to do the work, it would be wonderful.

Surely，thanks for you contributions of  Add-livere，Add-multi-language-support，Add-math-type-support and Fix-some-syntax-error. The related code has been added to the project

**Comment by Dinghow** [comment]
> @Dinghow
> 
> Hello, maybe you need to **redo** About-page and Friend-link-page，describe in detail how to use the gitalk script！
> 
> If you are willing to do the work, it would be wonderful.
> 
> Surely，thanks for you contributions of Add-livere，Add-multi-language-support，Add-math-type-support and Fix-some-syntax-error. The related code has been added to the project

OK, It's glad to see your update. I will do those jobs after this busy semester.

**Pull request closed without merging**
